codecov:
  notify:
    require_ci_to_pass: yes
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: True
      loop: True
      method: False
      changes: False
      macro: False

  comment:
    layout: "head, diff"
    behaviour: default
    require_change: no

